all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 10.0.1.100
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/lab-key-pair.pem
        web2:
          ansible_host: 10.0.1.101
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/lab-key-pair.pem
    databases:
      hosts:
        db1:
          ansible_host: 10.0.2.100
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/lab-key-pair.pem
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
