version: '3.8'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: 'localhost'
    ports:
      - '8080:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
    restart: always

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
